/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.entity.KhachHang;
import main.repository.ThemThongTinKhachHangRepository;
import org.apache.poi.hpsf.Array;

/**
 *
 * @author ADMIN
 */
public class ThemThongTinKhachHangJframe extends javax.swing.JFrame {
    private DefaultTableModel dtm = new DefaultTableModel();
    private ThemThongTinKhachHangRepository KHRP = new ThemThongTinKhachHangRepository();

    public static Integer id_tamKH;
    /**
     * Creates new form ThemThongTinKhachHangJframe
     */
    public ThemThongTinKhachHangJframe() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Thông Tin Khách Hàng - OSAKE");
        showDataTTKH(KHRP.getAll());
    }
    private void showDataTTKH(ArrayList<KhachHang> list_kh) {
        dtm = (DefaultTableModel) tbl_KhachHang1.getModel();
        dtm.setRowCount(0);
        AtomicInteger index = new AtomicInteger(1);
        list_kh.forEach(kh -> dtm.addRow(new Object[]{
            index.getAndIncrement(),
            kh.getMaKhachHang(),
            kh.getHoTen(),
            kh.getNgaySinh(),
            kh.isGioiTinh() ? "Nam" : "Nữ", 
            kh.getEmail(), 
            kh.getSoDienThoai(),
            kh.getDiaChi(),
            
        }
        ));
    }
    
   
    
    
    private KhachHang getFormDataKhachHang() {
//        // Lấy dữ liệu từ các trường
//        
//      

        String hoTen = txt_tenKhachHang.getText().trim();
        String diaChi = txt_DiaChi.getText().trim();
        String soDienThoai = txt_soDienThoai1.getText().trim();
        String email = txt_Email.getText().trim();
        String ngaySinh = new SimpleDateFormat("yyyy-MM-dd").format(jNgaySinh.getDate());
        

        // Kiểm tra xem tất cả các trường có bị bỏ trống không
        if (hoTen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Họ tên không được bỏ trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được bỏ trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        if (soDienThoai.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được bỏ trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }else if (!soDienThoai.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ. Vui lòng nhập lại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email không được bỏ trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        if(jNgaySinh.getDate().equals("")){
                JOptionPane.showMessageDialog(this, "Ngày sinh không được bỏ trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                jNgaySinh.requestFocus();
                return null;
        }        
        
        // Validate email
        String emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        Pattern pattern = Pattern.compile(emailPattern);
        Matcher matcher = pattern.matcher(email);
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        // Convert gender selection to Boolean
        Boolean gioiTinh = rdo_Nam.isSelected(); // true cho "Nam", false cho "Nữ"
//
//        // Build KhachHang object using Lombok's builder
        KhachHang kh = KhachHang.builder()
                .hoTen(hoTen)
                .diaChi(diaChi)
                .soDienThoai(soDienThoai)
                .email(email)
                .ngaySinh(ngaySinh)
                .gioiTinh(gioiTinh)
                .build();
////
        return kh;
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_KhachHang1 = new View.swing.Table();
        txt_TimTheoSDT1 = new javax.swing.JTextField();
        btn_timKhachHang1 = new com.Product.swing.ButtonBadges();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rdo_Nam = new javax.swing.JRadioButton();
        txt_soDienThoai1 = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        rdo_Nu = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_tenKhachHang = new javax.swing.JTextField();
        btn_ThemKH = new com.Product.swing.ButtonBadges();
        btn_Reset = new com.Product.swing.ButtonBadges();
        jNgaySinh = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(153, 153, 255));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));

        tbl_KhachHang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KH", "Họ và Tên", "Ngày Sinh", "Giới Tính", "Email", "SĐT ", "Địa Chỉ"
            }
        ));
        tbl_KhachHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_KhachHang1);

        txt_TimTheoSDT1.setBackground(new java.awt.Color(255, 255, 255));
        txt_TimTheoSDT1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TimTheoSDT1.setForeground(new java.awt.Color(0, 0, 0));

        btn_timKhachHang1.setBackground(new java.awt.Color(102, 102, 255));
        btn_timKhachHang1.setForeground(new java.awt.Color(255, 255, 255));
        btn_timKhachHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Timkiem.png"))); // NOI18N
        btn_timKhachHang1.setText("TÌM KIẾM");
        btn_timKhachHang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_timKhachHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKhachHangActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Lọc SĐT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(txt_TimTheoSDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_timKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TimTheoSDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane2.addTab("Danh Sách Khách Hàng", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        rdo_Nam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_Nam);
        rdo_Nam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdo_Nam.setForeground(new java.awt.Color(127, 127, 127));
        rdo_Nam.setText("NAM");
        rdo_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_NamActionPerformed(evt);
            }
        });

        txt_soDienThoai1.setBackground(new java.awt.Color(127, 127, 127));

        txt_Email.setBackground(new java.awt.Color(127, 127, 127));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(127, 127, 127));
        jLabel19.setText("Email:");

        txt_DiaChi.setBackground(new java.awt.Color(127, 127, 127));

        buttonGroup1.add(rdo_Nu);
        rdo_Nu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdo_Nu.setForeground(new java.awt.Color(127, 127, 127));
        rdo_Nu.setText("NỮ");
        rdo_Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_NuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 127, 127));
        jLabel4.setText("SĐT: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(127, 127, 127));
        jLabel9.setText("Họ và Tên");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(127, 127, 127));
        jLabel7.setText("Ngày sinh:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(127, 127, 127));
        jLabel18.setText("Giới Tính:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(127, 127, 127));
        jLabel17.setText("Địa Chỉ:");

        txt_tenKhachHang.setBackground(new java.awt.Color(127, 127, 127));

        btn_ThemKH.setBackground(new java.awt.Color(102, 102, 255));
        btn_ThemKH.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N
        btn_ThemKH.setText("THÊM ");
        btn_ThemKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemKHbtn_timKhachHangActionPerformed(evt);
            }
        });

        btn_Reset.setBackground(new java.awt.Color(102, 102, 255));
        btn_Reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/RESET.png"))); // NOI18N
        btn_Reset.setText("LÀM MỚI");
        btn_Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Resetbtn_timKhachHangActionPerformed(evt);
            }
        });

        jNgaySinh.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(35, 35, 35)
                        .addComponent(rdo_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(rdo_Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(btn_ThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7)
                    .addGap(8, 8, 8)
                    .addComponent(txt_soDienThoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(rdo_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rdo_Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jLabel7)
                    .addGap(37, 37, 37)
                    .addComponent(txt_soDienThoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(142, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Thiết Lập Thông Tin Khách Hàng Mới", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKhachHangActionPerformed
        String SDTcantim = txt_TimTheoSDT1.getText().trim();
        if(KHRP.timSDT(SDTcantim).isEmpty()){
            JOptionPane.showMessageDialog(this, "Không tìm thấy");
            
        }else{
            JOptionPane.showMessageDialog(this, "Có tìm thấy");
            this.showDataTTKH(KHRP.timSDT(SDTcantim));
        }
    }//GEN-LAST:event_btn_timKhachHangActionPerformed

    private void tbl_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhachHangMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tbl_KhachHang1.getSelectedRow();

        if (selectedRowIndex != -1) {
            // Lấy giá trị từ cột đầu tiên và kiểm tra kiểu dữ liệu
            Object value = tbl_KhachHang1.getValueAt(selectedRowIndex, 0);

            if (value instanceof Integer) {
                id_tamKH = (Integer) value;
                System.out.println("ID khách hàng: " + id_tamKH);
                // Đóng cửa sổ hiện tại nếu ID hợp lệ
                if (id_tamKH != null) {
                    this.dispose(); // Đóng cửa sổ hiện tại
                } else {
                    // Thông báo lỗi nếu id_tamKH là null
                    JOptionPane.showMessageDialog(this, "Mã khách hàng không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // Thông báo lỗi nếu giá trị không phải là Integer
                JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Hiển thị thông báo lỗi nếu không có hàng nào được chọn
            JOptionPane.showMessageDialog(this, "Không có hàng nào được chọn.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_tbl_KhachHangMouseClicked

    private void rdo_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_NamActionPerformed

    private void rdo_NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_NuActionPerformed

    private void btn_ThemKHbtn_timKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemKHbtn_timKhachHangActionPerformed
        KhachHang kh = getFormDataKhachHang();

        // Step 2: Perform validation
        List<KhachHang> existingKhachHangList = KHRP.getAll(); // Fetch all existing records

        // Check for empty fields
        if (kh.getHoTen() == null || kh.getHoTen().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Họ tên không được để trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (kh.getSoDienThoai() == null || kh.getSoDienThoai().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (kh.getEmail() == null || kh.getEmail().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email không được để trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check for duplicate email or phone number
        boolean emailExists = false;
        boolean phoneExists = false;

        for (KhachHang existingKh : existingKhachHangList) {
            if (existingKh.getEmail().equalsIgnoreCase(kh.getEmail())) {
                emailExists = true;
            }
            if (existingKh.getSoDienThoai().equals(kh.getSoDienThoai())) {
                phoneExists = true;
            }
        }

        if (emailExists) {
            JOptionPane.showMessageDialog(this, "Email đã tồn tại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (phoneExists) {
            JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Step 3: If validation passes, add the new KhachHang
        boolean result = KHRP.add(kh);
        if (result) {
            // Success message
            JOptionPane.showMessageDialog(this, "Khách hàng đã được thêm thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            // Step 4: Update the displayed data
            showDataTTKH(KHRP.getAll());
        } else {
            // Error message
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm khách hàng.", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ThemKHbtn_timKhachHangActionPerformed

    private void btn_Resetbtn_timKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Resetbtn_timKhachHangActionPerformed
        // TODO add your handling code here:
        txt_tenKhachHang.setText("");
        txt_Email.setText("");
        
        jNgaySinh.setDate(null);
        txt_soDienThoai1.setText("");
        txt_DiaChi.setText("");
        rdo_Nam.setSelected(true);
    }//GEN-LAST:event_btn_Resetbtn_timKhachHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinKhachHangJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinKhachHangJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinKhachHangJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinKhachHangJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemThongTinKhachHangJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.Product.swing.ButtonBadges btn_Reset;
    private com.Product.swing.ButtonBadges btn_ThemKH;
    private com.Product.swing.ButtonBadges btn_timKhachHang1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jNgaySinh;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton rdo_Nam;
    private javax.swing.JRadioButton rdo_Nu;
    private View.swing.Table tbl_KhachHang1;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_TimTheoSDT1;
    private javax.swing.JTextField txt_soDienThoai1;
    private javax.swing.JTextField txt_tenKhachHang;
    // End of variables declaration//GEN-END:variables
}
