/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

/**
 *
 * @author ADMIN
 */
public class ThemSanPhamChiTietJframe extends javax.swing.JFrame {

    /**
     * Creates new form ThemSanPhamChiTietJframe
     */
    public ThemSanPhamChiTietJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneBorder2 = new View.swing.PaneBorder();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_GiaBanSPCT = new javax.swing.JTextField();
        txt_SoLuongSPCT = new javax.swing.JTextField();
        txt_GiaNhapSPCT = new javax.swing.JTextField();
        btn_ThemSPCT = new com.Product.swing.ButtonBadges();
        btn_QuayLaiSPCT = new com.Product.swing.ButtonBadges();
        cbb_TenSPCT = new javax.swing.JComboBox<>();
        cbb_HangSPCT = new javax.swing.JComboBox<>();
        cbb_NamSPCT = new javax.swing.JComboBox<>();
        cbb_XuatxuSPCT = new javax.swing.JComboBox<>();
        cbb_LoaiRuouSPCT = new javax.swing.JComboBox<>();
        cbb_NongDoSPCT = new javax.swing.JComboBox<>();
        cbb_DungTichSPCT = new javax.swing.JComboBox<>();
        cbb_NCCSPCT = new javax.swing.JComboBox<>();
        btn_ThemNhanhTenSP = new View.swing.ButtonGradient();
        btn_ThemNhanhHangSX = new View.swing.ButtonGradient();
        btn_ThemNhanhNamSX = new View.swing.ButtonGradient();
        btn_ThemNhanhXuatXu = new View.swing.ButtonGradient();
        btn_ThemNhanhLoaiRuou = new View.swing.ButtonGradient();
        btn_ThemNhanhNongDo = new View.swing.ButtonGradient();
        btn_ThemNhanhDungTich = new View.swing.ButtonGradient();
        btn_ThemNhanhNCC = new View.swing.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneBorder2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("THÊM SẢN PHẨM CHI TIẾT");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Tên Sản Phẩm");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Hãng Sản Xuất");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Năm Sản Xuất");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Nồng Độ");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Dung Tích");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Loại Rượu");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Xuất Xứ");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Nhà Cung Cấp");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Số Lượng");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Giá Nhập");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Giá Bán");

        txt_GiaBanSPCT.setBackground(new java.awt.Color(255, 255, 255));
        txt_GiaBanSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_GiaBanSPCT.setForeground(new java.awt.Color(0, 0, 0));
        txt_GiaBanSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaBanSPCTtxt_HangSX3ActionPerformed(evt);
            }
        });

        txt_SoLuongSPCT.setBackground(new java.awt.Color(255, 255, 255));
        txt_SoLuongSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_SoLuongSPCT.setForeground(new java.awt.Color(0, 0, 0));

        txt_GiaNhapSPCT.setBackground(new java.awt.Color(255, 255, 255));
        txt_GiaNhapSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_GiaNhapSPCT.setForeground(new java.awt.Color(0, 0, 0));
        txt_GiaNhapSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaNhapSPCTtxt_tenSP3ActionPerformed(evt);
            }
        });

        btn_ThemSPCT.setBackground(new java.awt.Color(102, 102, 255));
        btn_ThemSPCT.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemSPCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N
        btn_ThemSPCT.setText("THÊM MỚI");
        btn_ThemSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemSPCTActionPerformed(evt);
            }
        });

        btn_QuayLaiSPCT.setBackground(new java.awt.Color(102, 102, 255));
        btn_QuayLaiSPCT.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuayLaiSPCT.setText("QUAY LẠI");
        btn_QuayLaiSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_QuayLaiSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuayLaiSPCTActionPerformed(evt);
            }
        });

        cbb_TenSPCT.setBackground(new java.awt.Color(255, 255, 255));
        cbb_TenSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbb_TenSPCT.setForeground(new java.awt.Color(0, 0, 0));

        cbb_HangSPCT.setBackground(new java.awt.Color(255, 255, 255));
        cbb_HangSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbb_HangSPCT.setForeground(new java.awt.Color(0, 0, 0));

        cbb_NamSPCT.setBackground(new java.awt.Color(255, 255, 255));
        cbb_NamSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbb_NamSPCT.setForeground(new java.awt.Color(0, 0, 0));

        cbb_XuatxuSPCT.setBackground(new java.awt.Color(255, 255, 255));
        cbb_XuatxuSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbb_XuatxuSPCT.setForeground(new java.awt.Color(0, 0, 0));

        cbb_LoaiRuouSPCT.setBackground(new java.awt.Color(255, 255, 255));
        cbb_LoaiRuouSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbb_LoaiRuouSPCT.setForeground(new java.awt.Color(0, 0, 0));

        cbb_NongDoSPCT.setBackground(new java.awt.Color(255, 255, 255));
        cbb_NongDoSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbb_NongDoSPCT.setForeground(new java.awt.Color(0, 0, 0));

        cbb_DungTichSPCT.setBackground(new java.awt.Color(255, 255, 255));
        cbb_DungTichSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbb_DungTichSPCT.setForeground(new java.awt.Color(0, 0, 0));

        cbb_NCCSPCT.setBackground(new java.awt.Color(255, 255, 255));
        cbb_NCCSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbb_NCCSPCT.setForeground(new java.awt.Color(0, 0, 0));

        btn_ThemNhanhTenSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N

        btn_ThemNhanhHangSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N

        btn_ThemNhanhNamSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N

        btn_ThemNhanhXuatXu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N

        btn_ThemNhanhLoaiRuou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N

        btn_ThemNhanhNongDo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N

        btn_ThemNhanhDungTich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N

        btn_ThemNhanhNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N

        javax.swing.GroupLayout paneBorder2Layout = new javax.swing.GroupLayout(paneBorder2);
        paneBorder2.setLayout(paneBorder2Layout);
        paneBorder2Layout.setHorizontalGroup(
            paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBorder2Layout.createSequentialGroup()
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBorder2Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel19))
                    .addGroup(paneBorder2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_QuayLaiSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(txt_GiaNhapSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(paneBorder2Layout.createSequentialGroup()
                                        .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                                .addComponent(cbb_LoaiRuouSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_ThemNhanhLoaiRuou, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel26)
                                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                                .addComponent(cbb_TenSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_ThemNhanhTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel21))
                                        .addGap(33, 33, 33)
                                        .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel31)
                                            .addComponent(txt_GiaBanSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                                .addComponent(cbb_NongDoSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_ThemNhanhNongDo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel22)
                                                    .addComponent(cbb_HangSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_ThemNhanhHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(59, 59, 59)
                                        .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_SoLuongSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel23)
                                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                                .addComponent(cbb_NamSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_ThemNhanhNamSX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                                .addComponent(cbb_DungTichSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_ThemNhanhDungTich, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel25))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbb_XuatxuSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_ThemSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel27)
                                    .addComponent(cbb_NCCSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ThemNhanhXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemNhanhNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        paneBorder2Layout.setVerticalGroup(
            paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(34, 34, 34)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneBorder2Layout.createSequentialGroup()
                        .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbb_NamSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_ThemNhanhNamSX, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbb_XuatxuSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_ThemNhanhXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(paneBorder2Layout.createSequentialGroup()
                        .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_ThemNhanhTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbb_TenSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_ThemNhanhHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(paneBorder2Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbb_HangSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)))
                        .addGap(16, 16, 16)))
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBorder2Layout.createSequentialGroup()
                        .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel24))
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_NongDoSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_DungTichSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneBorder2Layout.createSequentialGroup()
                        .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ThemNhanhDungTich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ThemNhanhNongDo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneBorder2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBorder2Layout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cbb_LoaiRuouSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btn_ThemNhanhLoaiRuou, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBorder2Layout.createSequentialGroup()
                                            .addComponent(jLabel28)
                                            .addGap(38, 38, 38))
                                        .addGroup(paneBorder2Layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn_ThemNhanhNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbb_NCCSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(2, 2, 2))))))
                        .addGap(34, 34, 34)))
                .addGap(23, 23, 23)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ThemSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneBorder2Layout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addGap(18, 18, 18)
                            .addComponent(txt_GiaNhapSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBorder2Layout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addGap(18, 18, 18)
                            .addComponent(txt_SoLuongSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneBorder2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(txt_GiaBanSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(btn_QuayLaiSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_GiaBanSPCTtxt_HangSX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaBanSPCTtxt_HangSX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GiaBanSPCTtxt_HangSX3ActionPerformed

    private void txt_GiaNhapSPCTtxt_tenSP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaNhapSPCTtxt_tenSP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GiaNhapSPCTtxt_tenSP3ActionPerformed

    private void btn_ThemSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemSPCTActionPerformed
        
    }//GEN-LAST:event_btn_ThemSPCTActionPerformed

    private void btn_QuayLaiSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuayLaiSPCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QuayLaiSPCTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamChiTietJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamChiTietJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamChiTietJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamChiTietJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSanPhamChiTietJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.Product.swing.ButtonBadges btn_QuayLaiSPCT;
    private View.swing.ButtonGradient btn_ThemNhanhDungTich;
    private View.swing.ButtonGradient btn_ThemNhanhHangSX;
    private View.swing.ButtonGradient btn_ThemNhanhLoaiRuou;
    private View.swing.ButtonGradient btn_ThemNhanhNCC;
    private View.swing.ButtonGradient btn_ThemNhanhNamSX;
    private View.swing.ButtonGradient btn_ThemNhanhNongDo;
    private View.swing.ButtonGradient btn_ThemNhanhTenSP;
    private View.swing.ButtonGradient btn_ThemNhanhXuatXu;
    private com.Product.swing.ButtonBadges btn_ThemSPCT;
    private javax.swing.JComboBox<String> cbb_DungTichSPCT;
    private javax.swing.JComboBox<String> cbb_HangSPCT;
    private javax.swing.JComboBox<String> cbb_LoaiRuouSPCT;
    private javax.swing.JComboBox<String> cbb_NCCSPCT;
    private javax.swing.JComboBox<String> cbb_NamSPCT;
    private javax.swing.JComboBox<String> cbb_NongDoSPCT;
    private javax.swing.JComboBox<String> cbb_TenSPCT;
    private javax.swing.JComboBox<String> cbb_XuatxuSPCT;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private View.swing.PaneBorder paneBorder2;
    private javax.swing.JTextField txt_GiaBanSPCT;
    private javax.swing.JTextField txt_GiaNhapSPCT;
    private javax.swing.JTextField txt_SoLuongSPCT;
    // End of variables declaration//GEN-END:variables
}
