/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

/**
 *
 * @author ADMIN
 */
public class ThongTinSanPhamJframe extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinSanPham1
     */
    public ThongTinSanPhamJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneBorder2 = new View.swing.PaneBorder();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_MaSPCT4 = new javax.swing.JTextField();
        txt_tenSP4 = new javax.swing.JTextField();
        txt_HangSX4 = new javax.swing.JTextField();
        txt_HangSX5 = new javax.swing.JTextField();
        txt_MaSPCT5 = new javax.swing.JTextField();
        txt_tenSP5 = new javax.swing.JTextField();
        txt_HangSX6 = new javax.swing.JTextField();
        txt_MaSPCT6 = new javax.swing.JTextField();
        txt_tenSP6 = new javax.swing.JTextField();
        txt_HangSX7 = new javax.swing.JTextField();
        txt_MaSPCT7 = new javax.swing.JTextField();
        txt_tenSP7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneBorder2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Thông Tin Sản Phẩm Chi Tiết");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Mã SPCT");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Tên Sản Phẩm");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Hãng Sản Xuất");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Năm Sản Xuất");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Nồng Độ");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Dung Tích");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Loại Rượu");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Xuất Xứ");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Nhà Cung Cấp");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Số Lượng");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Giá Nhập");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Giá Bán");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("QR SẢN PHẨM");

        txt_MaSPCT4.setBackground(new java.awt.Color(255, 255, 255));
        txt_MaSPCT4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MaSPCT4.setForeground(new java.awt.Color(0, 0, 0));

        txt_tenSP4.setBackground(new java.awt.Color(255, 255, 255));
        txt_tenSP4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_tenSP4.setForeground(new java.awt.Color(0, 0, 0));

        txt_HangSX4.setBackground(new java.awt.Color(255, 255, 255));
        txt_HangSX4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_HangSX4.setForeground(new java.awt.Color(0, 0, 0));
        txt_HangSX4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HangSX4txt_HangSXActionPerformed(evt);
            }
        });

        txt_HangSX5.setBackground(new java.awt.Color(255, 255, 255));
        txt_HangSX5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_HangSX5.setForeground(new java.awt.Color(0, 0, 0));
        txt_HangSX5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HangSX5txt_HangSX1ActionPerformed(evt);
            }
        });

        txt_MaSPCT5.setBackground(new java.awt.Color(255, 255, 255));
        txt_MaSPCT5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MaSPCT5.setForeground(new java.awt.Color(0, 0, 0));

        txt_tenSP5.setBackground(new java.awt.Color(255, 255, 255));
        txt_tenSP5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_tenSP5.setForeground(new java.awt.Color(0, 0, 0));

        txt_HangSX6.setBackground(new java.awt.Color(255, 255, 255));
        txt_HangSX6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_HangSX6.setForeground(new java.awt.Color(0, 0, 0));
        txt_HangSX6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HangSX6txt_HangSX2ActionPerformed(evt);
            }
        });

        txt_MaSPCT6.setBackground(new java.awt.Color(255, 255, 255));
        txt_MaSPCT6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MaSPCT6.setForeground(new java.awt.Color(0, 0, 0));

        txt_tenSP6.setBackground(new java.awt.Color(255, 255, 255));
        txt_tenSP6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_tenSP6.setForeground(new java.awt.Color(0, 0, 0));
        txt_tenSP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenSP6txt_tenSP2ActionPerformed(evt);
            }
        });

        txt_HangSX7.setBackground(new java.awt.Color(255, 255, 255));
        txt_HangSX7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_HangSX7.setForeground(new java.awt.Color(0, 0, 0));
        txt_HangSX7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HangSX7txt_HangSX3ActionPerformed(evt);
            }
        });

        txt_MaSPCT7.setBackground(new java.awt.Color(255, 255, 255));
        txt_MaSPCT7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MaSPCT7.setForeground(new java.awt.Color(0, 0, 0));

        txt_tenSP7.setBackground(new java.awt.Color(255, 255, 255));
        txt_tenSP7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_tenSP7.setForeground(new java.awt.Color(0, 0, 0));
        txt_tenSP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenSP7txt_tenSP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBorder2Layout = new javax.swing.GroupLayout(paneBorder2);
        paneBorder2.setLayout(paneBorder2Layout);
        paneBorder2Layout.setHorizontalGroup(
            paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBorder2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneBorder2Layout.createSequentialGroup()
                            .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24)
                                .addComponent(jLabel29)
                                .addComponent(txt_MaSPCT4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_tenSP4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27)
                                .addComponent(jLabel30)
                                .addComponent(txt_tenSP5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_tenSP6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_tenSP7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel32))
                            .addGap(134, 134, 134)
                            .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel31)
                                .addComponent(jLabel28)
                                .addComponent(jLabel25)
                                .addComponent(jLabel22)
                                .addComponent(txt_HangSX4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_HangSX5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_HangSX6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_HangSX7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(99, 99, 99))
                        .addGroup(paneBorder2Layout.createSequentialGroup()
                            .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_MaSPCT5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_MaSPCT6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(paneBorder2Layout.createSequentialGroup()
                        .addComponent(txt_MaSPCT7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(732, 732, 732))))
            .addGroup(paneBorder2Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneBorder2Layout.setVerticalGroup(
            paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBorder2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel19)
                .addGap(27, 27, 27)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenSP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaSPCT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_HangSX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenSP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaSPCT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_HangSX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenSP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaSPCT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_HangSX6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(paneBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenSP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaSPCT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_HangSX7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel32)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(paneBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_HangSX4txt_HangSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HangSX4txt_HangSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HangSX4txt_HangSXActionPerformed

    private void txt_HangSX5txt_HangSX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HangSX5txt_HangSX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HangSX5txt_HangSX1ActionPerformed

    private void txt_HangSX6txt_HangSX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HangSX6txt_HangSX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HangSX6txt_HangSX2ActionPerformed

    private void txt_tenSP6txt_tenSP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenSP6txt_tenSP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenSP6txt_tenSP2ActionPerformed

    private void txt_HangSX7txt_HangSX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HangSX7txt_HangSX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HangSX7txt_HangSX3ActionPerformed

    private void txt_tenSP7txt_tenSP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenSP7txt_tenSP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenSP7txt_tenSP3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinSanPhamJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private View.swing.PaneBorder paneBorder2;
    private javax.swing.JTextField txt_HangSX4;
    private javax.swing.JTextField txt_HangSX5;
    private javax.swing.JTextField txt_HangSX6;
    private javax.swing.JTextField txt_HangSX7;
    private javax.swing.JTextField txt_MaSPCT4;
    private javax.swing.JTextField txt_MaSPCT5;
    private javax.swing.JTextField txt_MaSPCT6;
    private javax.swing.JTextField txt_MaSPCT7;
    private javax.swing.JTextField txt_tenSP4;
    private javax.swing.JTextField txt_tenSP5;
    private javax.swing.JTextField txt_tenSP6;
    private javax.swing.JTextField txt_tenSP7;
    // End of variables declaration//GEN-END:variables
}
